### PR TITLE
Update README.md

### LINKED ISSUE #3: Properties with dashes cannot be passed through environment variables
I tried to set `openapi-ui.yamlUrl` property with env variable, but it is impossible to use dashes in bash variables. Am I wrong? Is there are chance for changing properties not to use dashes?

### PR DESCRIPTION
**Pull request by kret11**
Resolves #3

### CODE REVIEW

**Comment by phillip-kruger** [comment]
Thanks. While you at it - fix the the example too :)

**Comment by kret11** [comment]
> 
> 
> Thanks. While you at it - fix the the example too :)

i dont think there is need for any fix in example. can you please upload new version to mvnrepository.com?

**Comment by kret11** [comment]
@phillip-kruger or if you cannot today, maybe you can approx time? ;)

**Comment by phillip-kruger** [comment]
@kret11 - Yes busy looking to do that. Getting a weird error in travis (https://travis-ci.com/microprofile-extensions/openapi-ext/builds/117123437). Looking at it now.

**Comment by phillip-kruger** [comment]
Cool. 1.0.2 is available in https://oss.sonatype.org/#nexus-search;quick~microprofile-ext.openapi-ext.
It takes a few hours to reflect in maven central but should be there soon.

Thanks

**Comment by kret11** [comment]
thank you very much

**Pull request merged**
